### ISSUE TITLE
Cannot invoke "java.nio.file.Path.getFileSystem()" because "path" is null

### ISSUE THREAD

**Issue by maso222** [Proximity-Engine/Proximity#38]
running jdk 17.0.1 and proximity 0.4.0 is working 
but proximity 0.5.0 and 0.5.1 not working, getting below messages:
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by dev.hephaestus.proximity.Main
WARNING: Please consider reporting this to the maintainers of dev.hephaestus.proximity.Main
WARNING: System::setSecurityManager will be removed in a future release
ERROR [Proximity] Cannot invoke "java.nio.file.Path.getFileSystem()" because "path" is null

**Comment by Haven-King** [comment]
Which template are you using? Could you post your deck list and the command you run as well?

**Comment by lopitals** [comment]
Hi, I got the same message than maso222 and I'm using chillis-0.4.0, and jdk-17.0.1.

**Comment by Haven-King** [comment]
Proximity 0.5.x requires the updated master template:
https://github.com/Proximity-Engine/M15-Master-Template/releases/tag/1.0.2

**Comment by lopitals** [comment]
Hi,

Now proximity creates the cards, but keeps the warning:

WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by dev.hephaestus.proximity.Main (file:/D:/Docs/MPC/Proximity/proximity-0.5.1.jar)
WARNING: Please consider reporting this to the maintainers of dev.hephaestus.proximity.Main
WARNING: System::setSecurityManager will be removed in a future release

And is creating the back for not double-faced cards.

The command I'm using is:

java -jar proximity-0.5.1.jar --cards=deck.txt --use_official_art=true --reminder_text=true --template=M15-Master-Template-1.0.2 --threads=4 --copyright=false

Thanks.

**Comment by Haven-King** [comment]
Yes, that warning is a separate matter and can be safely ignored.

**Comment by DuyKhoiCoder30062004** [comment]
help me pleaes, i have the same problem in netbeans 13
