### ISSUE TITLE
Colorless Cards

### ISSUE THREAD

**Issue by Phobia9651** [Proximity-Engine/Proximity#42]
First of all I love all the work you've put into this tool.
Now I was wondering if there is a way to trick the tool to use the artifact frame for colorless cards, like Devoid cards?
Cause right now it returns a transparent frame, while still using the crop art rather than the full art.

**Comment by Haven-King** [comment]
It would be somewhat involved to do so. Another solution I'd recommend would be to use `--art_source=NONE` and add the art yourself afterwards.

**Comment by Phobia9651** [comment]
Thank you for the tip, however is there a way copy+rename files in the template folder so they will be used by Proximity when processing (non-land, non-artifact) colourless cards?
Cause I am okay with not having full art on colourless cards, but I would just like to see a visible outer frame on them (ie. the part that is white/blue/black/red/green/gold/grey/brown).

**Comment by Phobia9651** [comment]
I tried changing the colorless.png in the "templates\Extended\backgrounds\standard" to something of my own liking, but somehow that frame is never applied to the cards. I tried it for 2 different templates with the same endresult (the M15 and Extended).
Is the background skipped for colorless cards altogether?

**Comment by Haven-King** [comment]
Yes, the background is skipped for colorless non-land, non-artifact cards (as there does not exist a "colorless bordered" card).

**Comment by Phobia9651** [comment]
Would it be possible to provide that option anyway? Since all the templates I've seen actually supply a background frame for colorless cards.

**Comment by Haven-King** [comment]
This is up to the template itself. The M15-Master-Template doesn't have that option, but any other template could add it easily.

**Comment by Phobia9651** [comment]
Cheers, I will look into the XML files of the templates I am using.

**Comment by Phobia9651** [comment]
It was as simple as adding:
<Image id="colorless"/>
At the correct spot in the XML.
Thanks for your help and keep up the great work you're doing for the proxy community.
